### ISSUE TITLE
Getting so many errors

### ISSUE THREAD

**Issue by dheerajbred** [crazecoder/flutter_gsyplayer#2]
I pasted the same code in the example/lib/main.dart in a new project and imported the git library.

https://prnt.sc/n3cgp4

and when I click, video doesn't play.

```
E/flutter (31091): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method play on channel flutter_gsyplayer)
E/flutter (31091): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #1      play (package:flutter_gsyplayer/flutter_gsyplayer.dart:15:18)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #2      _VideoPlayerPageState.initState (package:ProPapers/videopage.dart:219:1)
E/flutter (31091): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter (31091): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (31091): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (31091): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (31091): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (31091): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (31091): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (31091): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (31091): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (31091): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (31091): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (31091): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (31091): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (31091): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (31091): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (31091): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (31091): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (31091): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (31091): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (31091): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (31091): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (31091): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (31091): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (31091): #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (31091): #45     Compo
E/flutter (31091): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method onBackPress on channel flutter_gsyplayer)
E/flutter (31091): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #1      GSYPlayer._listenOnBackPress (package:flutter_gsyplayer/flutter_gsyplayer.dart:41:20)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #2      new GSYPlayer (package:flutter_gsyplayer/flutter_gsyplayer.dart:56:5)
E/flutter (31091): #3      _VideoPlayerPageState.build (package:ProPapers/videopage.dart:621:18)
E/flutter (31091): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
E/flutter (31091): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
E/flutter (31091): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (31091): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (31091): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (31091): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (31091): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (31091): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (31091): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (31091): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (31091): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (31091): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (31091): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (31091): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (31091): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (31091): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (31091): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (31091): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (31091): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (31091): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (31091): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (31091): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (31091): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (31091): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (31091): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (31091): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (31091): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:295
E/flutter (31091): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Trying to create a platform view of unregistered type: gsyplayer, null)
E/flutter (31091): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (31091): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:580:54)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:505:14)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:178:29)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:159:5)
E/flutter (31091): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:9)
E/flutter (31091): #7      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
E/flutter (31091): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #9      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
E/flutter (31091): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #11     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
E/flutter (31091): #12     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:350:7)
E/flutter (31091): #13     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
E/flutter (31091): #14     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
E/flutter (31091): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
E/flutter (31091): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
E/flutter (31091): #19     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1203:11)
E/flutter (31091): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
E/flutter (31091): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
E/flutter (31091): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
E/flutter (31091): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
E/flutter (31091): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
E/flutter (31091): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
E/flutter (31091): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
E/flutter (31091): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (31091): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
E/flutter (31091): #36
E/flutter (31091): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method onBackPress on channel flutter_gsyplayer)
E/flutter (31091): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #1      GSYPlayer._listenOnBackPress (package:flutter_gsyplayer/flutter_gsyplayer.dart:41:20)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #2      new GSYPlayer (package:flutter_gsyplayer/flutter_gsyplayer.dart:56:5)
E/flutter (31091): #3      _VideoPlayerPageState.build (package:ProPapers/videopage.dart:621:18)
E/flutter (31091): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
E/flutter (31091): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
E/flutter (31091): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (31091): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
E/flutter (31091): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:691:20)
E/flutter (31091): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
E/flutter (31091): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
E/flutter (31091): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
E/flutter (31091): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
E/flutter (31091): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (31091): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (31091): #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (31091): #16     _invoke (dart:ui/hooks.dart:189:10)
E/flutter (31091): #17     _drawFrame (dart:ui/hooks.dart:162:3)
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method onBackPress on channel flutter_gsyplayer)
E/flutter (31091): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #1      GSYPlayer._listenOnBackPress (package:flutter_gsyplayer/flutter_gsyplayer.dart:41:20)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #2      new GSYPlayer (package:flutter_gsyplayer/flutter_gsyplayer.dart:56:5)
E/flutter (31091): #3      _VideoPlayerPageState.build (package:ProPapers/videopage.dart:621:18)
E/flutter (31091): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
E/flutter (31091): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
E/flutter (31091): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (31091): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
E/flutter (31091): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:691:20)
E/flutter (31091): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
E/flutter (31091): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
E/flutter (31091): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
E/flutter (31091): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
E/flutter (31091): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (31091): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (31091): #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (31091): #16     _invoke (dart:ui/hooks.dart:189:10)
E/flutter (31091): #17     _drawFrame (dart:ui/hooks.dart:162:3)
E/flutter (31091): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(load_failed_ad, cannot reload a failed ad, id=766246666, null)
E/flutter (31091): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (31091): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:500:61)
E/flutter (31091): <asynchronous suspension>
E/flutter (31091): #3      InterstitialAd.load (package:firebase_admob/firebase_admob.dart:289:12)
E/flutter (31091): #4      MyApp.build.<anonymous closure> (package:ProPapers/main.dart:84:23)
E/flutter (31091): #5      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (31091): #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (31091): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (31091): #8      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:26)
E/flutter (31091): #9      _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (31091): #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (31091): #11     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:952:26)
E/flutter (31091): #12     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (31091): #13     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (31091): #14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Any idea how to this?

Any type of suggestion is appreciated.

**Comment by crazecoder** [comment]
Androidx has some problems, now it has been rolled back to support. If you are androidx,use this
 [flutter_ijkplayer_beta](https://github.com/crazecoder/flutter_ijkplayer_beta)

**Comment by dheerajbred** [comment]
I am not using androidX

**Comment by crazecoder** [comment]
u can upgrade and try it again
